'use client';

import { StatCard } from '@/components/StatCard';
import { TrendStat } from '@/components/TrendStat';
import { TimeSeriesChart } from '@/components/TimeSeriesChart';
import { GettingStarted } from '@/components/GettingStarted';
import { QueryState } from '@/components/QueryState';
import { useOverview, useMauBill, useMe } from '@/hooks/useDashboard';
import { money, num } from '@/lib/format';

function greeting(): string {
  const h = new Date().getHours();
  if (h < 12) return 'Good morning';
  if (h < 17) return 'Good afternoon';
  return 'Good evening';
}

function nameFromEmail(email?: string): string {
  if (!email) return 'there';
  const raw = email.split('@')[0].replace(/[._-]+/g, ' ').trim();
  return raw.charAt(0).toUpperCase() + raw.slice(1);
}

export default function OverviewPage() {
  const overview = useOverview();
  const mau = useMauBill();
  const me = useMe();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">
          {greeting()}, {nameFromEmail(me.data?.account.email)}
        </h1>
        <p className="mt-0.5 text-sm text-muted">Here's a snapshot of how your product tours are performing.</p>
      </div>

      <QueryState query={overview}>
        {(d) => (
          <>
            <GettingStarted hasTours={d.toursGenerated > 0} hasViews={d.toursShownWeek > 0} />

            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <TrendStat
                label="Active users"
                value={num(d.trend.activeUsersWeek)}
                deltaPct={d.trend.activeUsersDeltaPct}
                hint="this week"
              />
              <TrendStat
                label="Tours shown"
                value={num(d.toursShownWeek)}
                deltaPct={d.trend.shownDeltaPct}
                hint={`${num(d.stepsShownWeek)} steps shown to end users`}
              />
              <StatCard
                label="Tours generated"
                value={num(d.toursGenerated)}
                hint={`${num(d.totalSteps)} total steps generated by AI`}
                highlight
              />
            </div>

            <TimeSeriesChart />
          </>
        )}
      </QueryState>

      <div>
        <h2 className="mb-3 text-sm font-medium text-muted">This month</h2>
        <QueryState query={mau}>
          {(b) => (
            <div className="grid grid-cols-2 gap-4 md:grid-cols-3">
              <StatCard label="Active users" value={num(b.mau)} hint={`Plan: ${b.plan}`} />
              <StatCard label="Amount due" value={money(b.amountDue)} hint={`Next bill on ${new Date(new Date().getFullYear(), new Date().getMonth() + 1, 1).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`} />
              <StatCard
                label="Plan limit"
                value={b.planLimit === null ? 'Unlimited' : num(b.planLimit)}
                hint={b.overage ? `Overage: ${money(b.overage)}` : `Within limit · ${num(b.planLimit - b.mau)} remaining`}
              />
            </div>
          )}
        </QueryState>
      </div>
    </div>
  );
}
